# Generated by Django 4.2.5 on 2023-10-08 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='skey',
        ),
    ]
