# Generated by Django 4.2.5 on 2023-10-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_remove_wallet_skey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='hint',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='User key hint'),
        ),
    ]
