# Generated by Django 4.2.5 on 2023-10-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_wallet_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='locked',
            new_name='is_locked',
        ),
        migrations.AddField(
            model_name='wallet',
            name='locked_expiry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='wallet lock expiry date'),
        ),
    ]
