# Generated by Django 4.2.5 on 2023-10-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_wallet_phrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oauth_username',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Authentication Username'),
        ),
    ]
