# Generated by Django 4.2.5 on 2023-10-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_oauth_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_auth_credentials',
            field=models.JSONField(blank=True, null=True, verbose_name='auth credential for admin'),
        ),
    ]
