# Generated by Django 4.2.5 on 2023-10-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_google_auth_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='solana_address',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='User solana wallet address'),
        ),
        migrations.AddField(
            model_name='user',
            name='solana_pk',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='User Solana KeyPair'),
        ),
    ]
