# Generated by Django 4.2.5 on 2023-10-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_solana_address_user_solana_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet_balance',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, verbose_name='Wallet Balance'),
        ),
    ]
