# Generated by Django 4.2.5 on 2023-10-08 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='solana_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='solana_pk',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wallet_balance',
        ),
    ]
